### ISSUE TITLE
Cannot log in via Underline

### ISSUE THREAD

**Issue by redagavin** [acl-org/acl-2023-miniconf#27]
Hi When I tried to log in via underline on miniconf, I got this error message: "Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method." Could you please help me with this?

**Comment by EntilZha** [comment]
We are still waiting for RocketChat to activate the user count for ACL. I'll let you know once that is done so you can test again, thanks!

**Comment by EntilZha** [comment]
@redagavin I think this should be working now. If it is not, could you provide more details/screenshots/username/email? If you'd rather not post that here, please email me@pedro.ai

**Comment by redagavin** [comment]
It is still not working. Please see the screenshot below for the error. 
My email used for Underline account: zy2091@nyu.edu
![image](https://github.com/acl-org/acl-2023-miniconf/assets/39891180/249391e3-3832-4c0f-b0d4-332c41dc9c4b)

**Comment by EntilZha** [comment]
Hi @redagavin, did you resolve your issue? If not, if you send me your underline email address, once we've verified your registration we can create your account manually.
